#!/bin/bash

: << =cut
=head1 NAME

verm_requests - Plugin to monitor the number of requests processed by Verm

=head1 AUTHOR

Will Bryant

=head1 LICENSE

MIT
=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo -e "GET /_statistics HTTP/1.0\n" | nc localhost 3404 >/dev/null
	if [ $? == "0" ]; then
		echo yes
		exit 0
	else
		echo no
		exit 0
	fi
fi

data=`echo -e "GET /_statistics HTTP/1.0\n" | nc localhost 3404 | grep _ | grep -v connections_current | grep -v queue_length | grep -v "#" | sed -E 's/verm_|_total//g'`

if [ "$1" = "config" ]; then
	echo 'graph_title Verm requests'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel requests / ${graph_period}'
	echo 'graph_category verm'
	echo 'graph_info This graph shows the number of requests processed by Verm.'
	echo 'get_requests.label GET requests served'
	echo 'get_requests_found_on_replica.label GET requests found on replica'
	echo 'get_requests_not_found.label GET requests not found'
	echo 'post_requests.label POST requests served'
	echo 'post_requests_new_file_stored.label POST requests resulting in a new file stored'
	echo 'post_requests_failed.label POST requests failed'
	echo 'put_requests.label PUT requests served'
	echo 'put_requests_new_file_stored.label PUT requests resulting in a new file stored'
	echo 'put_requests_missing_file_checks.label PUT requests checking for missing files'
	echo 'put_requests_failed.label PUT requests failed'
	echo 'replication_push_attempts.label Replication push attempts'
	echo 'replication_push_attempts_failed.label Replication push attempts failed'
	echo "$data" | awk '{ print $1 ".type DERIVE\n" $1 ".min 0" }'
	exit 0
fi

echo "$data" | awk '{ print $1 ".value " $2 }'
