#!/bin/bash

: << =cut
=head1 NAME

verm_replication_queue - Plugin to monitor the number of files in the Verm replication queues

=head1 AUTHOR

Will Bryant

=head1 LICENSE

MIT
=cut

. $MUNIN_LIBDIR/plugins/plugin.sh

if [ "$1" = "autoconf" ]; then
	echo -e "GET /_statistics HTTP/1.0\n" | nc localhost 3404 >/dev/null
	if [ $? == "0" ]; then
		echo yes
		exit 0
	else
		echo no
		exit 0
	fi
fi

data=`echo -e "GET /_statistics HTTP/1.0\n" | nc localhost 3404 | grep queue_length | grep -v "#"`
data=`echo "$data" | sed -E 's/verm_replication_queue_length\{target="(.*):([0-9]+)"\}/replication_\1_\2_queue_length/g'`

if [ "$1" = "config" ]; then
	echo 'graph_title Verm replication queue length'
	echo 'graph_args --base 1000 -l 0'
	echo 'graph_vlabel Files in queue'
	echo 'graph_category verm'
	echo 'graph_info This graph shows the number of files in the queue to be replicated to each configured replica.'
	echo "$data" | sed -E 's/replication_(.+)_([0-9]+)_queue_length .*/replication_\1_\2_queue_length.label \1:\2/'
	exit 0
fi

echo "$data" | awk '{ if ($0!="") print $1 ".value " $2 }'
